bind -N "Harpoon: Start tracking current window" a    run 'harpoon -a'
bind -N "Harpoon: Start tracking current pane"   .    run 'harpoon -A'
bind -N "Harpoon: List tracked windows in fzf"   f    run 'harpoon -l'
bind -N "Harpoon: Edit tracked windows"          C-e  run 'harpoon -e'
bind -N "Harpoon: Select window 1"               C-h  run 'harpoon -s 1'
bind -N "Harpoon: Select window 2"               C-j  run 'harpoon -s 2'
bind -N "Harpoon: Select window 3"               C-k  run 'harpoon -s 3'
bind -N "Harpoon: Select window 4"               C-l  run 'harpoon -s 4'
