bind -N "Harpoon: Start tracking current window" C-_    run 'x tmux harpoon add'
bind -N "Harpoon: Start tracking current pane"   .    run 'x tmux harpoon pane'
bind -N "Harpoon: List tracked windows in fzf"   f    run 'x tmux harpoon list'
bind -N "Harpoon: Edit tracked windows"          C-e  run 'x tmux harpoon edit'
bind -N "Harpoon: Select window 1"               C-h  run 'x tmux harpoon go 1'
bind -N "Harpoon: Select window 2"               C-j  run 'x tmux harpoon go 2'
bind -N "Harpoon: Select window 3"               C-k  run 'x tmux harpoon go 3'
bind -N "Harpoon: Select window 4"               C-l  run 'x tmux harpoon go 4'
