[general]
live_config_reload = true
import = [
        "~/.config/alacritty/themes/material-rosepine.toml",
        "~/.config/alacritty/fonts/monolisa-nerd-font.toml",
]

[colors]
draw_bold_text_with_bright_colors = true

[cursor.style]
shape = "Block"
blinking = "Never"

[cursor.vi_mode_style]
shape = "Block"
blinking = "Never"

[env]
LANG = "en_US.UTF-8"
LC_ALL = "en_US.UTF-8"
TERM = "alacritty"

[mouse]
hide_when_typing = true

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true

[terminal.shell]
args = ["-l", "-c", "tmux new -As home; /bin/zsh -l"]
program = "/bin/zsh"

[window]
decorations = "none"
opacity = 0.95
blur = true
startup_mode = "Maximized"
