[font]
builtin_box_drawing = true
size = 10.2

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "ExtraBold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style = "ExtraBold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Light"

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 2
y = 0
