[font]
builtin_box_drawing = true
size = 14.9

[font.bold]
family = "MonoLisa Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "MonoLisa Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "MonoLisa Nerd Font Mono"
style = "Regular Italic"

[font.normal]
family = "MonoLisa Nerd Font Mono"
style = "Regular"

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = 0
