#!/bin/sh

_have() { type "$1" >/dev/null 2>&1; }

# Use as an alias to disable builtin commands
donothing() { echo "$*" >/dev/null 2>&1; }

alias mkdir='mkdir -pv'
alias view='vi -R'

_have /usr/bin/vim && alias vi=/usr/bin/vim
_have /usr/local/bin/nvim && alias vim=/usr/local/bin/nvim vimdiff='vim -d'
_have bat && alias cat='bat'

md() { [ -z "$1" ] && exit 1 || mkdir -p "$1" && cd "$1" || return; }

_have note && {
	alias bm='note -b'
	alias did='note -c'
	alias todo='note -t'
}

_have docker && {
	alias d='docker'
	alias dps='docker ps'
	alias di='docker images'
}

_have fd && _have fzf && {
	edit() {
		fd . -Ht f -d 6 -E .git -E .DS_Store |
			fzf --height=20% --border --margin=0 --padding=0 \
				--bind='enter:become(nvim {})'
	}
	_have workdirs && {
		j() {
			program="${1:-cd}"
			selected="$(workdirs -s | fzf --height=20% --border --margin=0 --padding=0)"
			$program "$(workdirs | grep -w "$selected$")"
		}
	}
}
