#!/bin/sh

_distro() {
	if [ -f /etc/os-release ]; then
		# shellcheck disable=SC1091
		. /etc/os-release
		DISTRO=$NAME
		VERSION=$VERSION_ID
	elif type lsb_release >/dev/null 2>&1; then
		DISTRO=$(lsb_release -si)
		VERSION=$(lsb_release -sr)
	else
		DISTRO=$(uname -s)
		VERSION=$(uname -r)
	fi

	echo "$DISTRO:$VERSION"
}

_have() { { type "$1" >/dev/null 2>&1; } || [ -n "$DOTSETUP" ]; }

_ismac() { [ "$(uname)" = "Darwin" ]; }

_islinux() { [ "$(uname -s | cut -c 1-5)" = "Linux" ]; }

DISTRO="$(_distro | cut -d : -f1)"

export NOTESPATH="$HOME"/projects/library
export DOWNLOADS="$HOME/downloads"
export SCRIPTS="$HOME/.local/bin"
export DOTFILES="$HOME/dotfiles"

export XDG_DATA_HOME="$HOME"/.local/share
export XDG_STATE_HOME="$HOME"/.local/state
export XDG_CACHE_HOME="$HOME"/.local/cache
export XDG_CONFIG_HOME="$HOME"/.config

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
export LC_TYPE=UTF-8
export LC_CTYPE=UTF-8

export VISUAL="nvim"
export EDITOR="$VISUAL"

export GOPATH="$HOME"/programs/go
export GOBIN="$GOPATH"/bin

export FVM_CACHE_PATH="$HOME"/programs/flutter
export FLUTTER_SDK_ROOT="$FVM_CACHE_PATH"/default
_islinux && export ANDROID_SDK_ROOT="$HOME/programs/android"
_islinux && export ANDROID_HOME="$HOME/programs/android"
case "$DISTRO" in
Debian | Ubuntu) export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64 ;;
Arch\ Linux) export JAVA_HOME=/usr/lib/jvm/java-17-openjdk ;;
*) if _ismac; then JAVA_HOME="$(/usr/libexec/java_home)" && export JAVA_HOME; fi ;;
esac
_ismac && export ANDROID_SDK_ROOT="$HOME"/Library/Android/Sdk
_ismac && export LDFLAGS="-L/opt/homebrew/opt/llvm/lib"
_ismac && export CPPFLAGS="-I/opt/homebrew/opt/llvm/include"
_ismac && _have jira && JIRA_API_TOKEN="$(cat ~/.secrets/jira-token)" && export JIRA_API_TOKEN

_have fzf && . "$(dirname "$0")"/fzfrc

_have bat && export BAT_THEME="material-rose-pine"
