#!/bin/sh

_distro() {
	if [ -f /etc/os-release ]; then
		# shellcheck disable=SC1091
		. /etc/os-release
		DISTRO=$NAME
		VERSION=$VERSION_ID
	elif type lsb_release >/dev/null 2>&1; then
		DISTRO=$(lsb_release -si)
		VERSION=$(lsb_release -sr)
	else
		DISTRO=$(uname -s)
		VERSION=$(uname -r)
	fi

	echo "$DISTRO:$VERSION"
}

_ismac() { [ "$(uname)" = "Darwin" ]; }

_islinux() { [ "$(uname -s | cut -c 1-5)" = "Linux" ]; }

DISTRO="$(_distro | cut -d : -f1)"

export NOTESPATH="$HOME"/projects/notes
export DOWNLOADS="$HOME/downloads"
export SCRIPTS="$HOME/.local/bin"
export DOTFILES="$HOME/dotfiles"

export XDG_DATA_HOME="$HOME"/.local/share
export XDG_STATE_HOME="$HOME"/.local/state
export XDG_CACHE_HOME="$HOME"/.local/cache
export XDG_CONFIG_HOME="$HOME"/.config

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
export LC_TYPE=UTF-8
export LC_CTYPE=UTF-8

export VISUAL="nvim"
export EDITOR="$VISUAL"

export GOPATH="$HOME"/programs/go
export GOBIN="$GOPATH"/bin

export FLUTTER_SDK_ROOT="$FVM_CACHE_PATH"/default
export FVM_CACHE_PATH="$HOME"/programs/flutter
_islinux && export ANDROID_SDK_ROOT="$HOME/programs/android"
_islinux && export ANDROID_HOME="$HOME/programs/android"
case "$DISTRO" in
Debian | Ubuntu) export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64 ;;
Arch\ Linux) export JAVA_HOME=/usr/lib/jvm/java-17-openjdk ;;
*) if _ismac; then JAVA_HOME="$(/usr/libexec/java_home)" && export JAVA_HOME; fi ;;
esac
_ismac && export ANDROID_SDK_ROOT="$HOME"/Library/Android/Sdk
_ismac && export LDFLAGS="-L/opt/homebrew/opt/llvm/lib"
_ismac && export CPPFLAGS="-I/opt/homebrew/opt/llvm/include"

export BAT_THEME="Visual Studio Dark+"
export FZF_DEFAULT_COMMAND='fd --type file --hidden --exclude .git'

# Material deep ocean colors
# export FZF_DEFAULT_OPTS="
#    --cycle --info=hidden
#    --prompt='▍' --pointer='▍' --tabstop=4
#    --color=fg:#a6accd,bg:#0f111a,hl:#464b5d
#    --color=fg+:#a6accd,bg+:#0f111a,hl+:#89ddff
#    --color=info:#0f111a,prompt:#c792ea,pointer:#f07178
#    --color=marker:#c792ea,spinner:#c792ea,header:#464b5d
#    --color=preview-bg:#090b10,border:#464b5d"

# Rose pine colors
# export FZF_DEFAULT_OPTS="
#    --cycle --info=hidden
#    --prompt='▍' --pointer='▍' --tabstop=4
#    --color=fg:#908caa,bg:#191724,hl:#ebbcba
#    --color=fg+:#e0def4,bg+:#26233a,hl+:#ebbcba
#    --color=border:#403d52,header:#31748f,gutter:#191724
#    --color=spinner:#f6c177,info:#9ccfd8,separator:#403d52
#    --color=pointer:#c4a7e7,marker:#eb6f92,prompt:#908caa"

# Material rosepine colors
export FZF_DEFAULT_OPTS="
    --cycle --info=hidden
    --prompt='▍' --pointer='▍' --tabstop=4
    --color=fg:#908caa,bg:#0f111a,hl:#ebbcba
    --color=fg+:#e0def4,bg+:#0f111a,hl+:#ebbcba
    --color=border:#403d52,header:#31748f,gutter:#0f111a
    --color=spinner:#f6c177,info:#9ccfd8,separator:#403d52
    --color=pointer:#c4a7e7,marker:#eb6f92,prompt:#908caa"

export FZF_CTRL_R_OPTS="
    --info=inline --border --reverse
    --preview 'echo {}' --preview-window up:3:hidden:wrap
    --bind 'ctrl-/:toggle-preview'
    --bind 'ctrl-y:execute-silent(echo -n {2..} | pbcopy)+abort'
    --color header:italic
    --header 'Press CTRL-Y to copy command into clipboard'"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_CTRL_T_OPTS="
    --info=hidden --border
    --preview 'bat -n --color=always {}'
    --bind 'ctrl-/:change-preview-window(down|hidden|)'"
export FZF_ALT_C_COMMAND="fd . -t d --hidden"
export FZF_ALT_C_OPTS="--preview='eza --tree {} | head -50'"
