#!/bin/sh

prepend_path() {
	case ":$PATH:" in
	*:"$1":*) ;;
	::) [ -d "$1" ] && export PATH="$1" ;;
	*) [ -d "$1" ] && export PATH="$1:$PATH" ;;
	esac
}

append_path() {
	case ":$PATH:" in
	*:"$1":*) ;;
	::) [ -d "$1" ] && export PATH="$1" ;;
	*) [ -d "$1" ] && export PATH="$PATH:$1" ;;
	esac
}

_ismac() { [ "$(uname)" = "Darwin" ]; }
_islinux() { [ "$(uname -s | cut -c 1-5)" = "Linux" ]; }

export NOTESPATH="$HOME"/projects/notes
export DOWNLOADS="$HOME/downloads"
export SCRIPTS="$HOME/.local/bin"

export XDG_DATA_HOME="$HOME"/.local/share
export XDG_STATE_HOME="$HOME"/.local/state
export XDG_CACHE_HOME="$HOME"/.local/cache
export XDG_CONFIG_HOME="$HOME"/.config

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
export LC_TYPE=UTF-8
export LC_CTYPE=UTF-8

export VISUAL="nvim"
export EDITOR="$VISUAL"

export GOPATH="$HOME"/programs/go
export GOBIN="$GOPATH"/bin

export FLUTTER_SDK_ROOT="$HOME"/fvm/default
_ismac && export ANDROID_SDK_ROOT="$HOME"/Library/Android/Sdk
_ismac && JAVA_HOME="$(/usr/libexec/java_home)" && export JAVA_HOME
_ismac && export LDFLAGS="-L/opt/homebrew/opt/llvm/lib"
_ismac && export CPPFLAGS="-I/opt/homebrew/opt/llvm/include"

export BAT_THEME="Visual Studio Dark+"
export FZF_DEFAULT_COMMAND='fd --type file --hidden --exclude .git'

# Material deep ocean colors
# export FZF_DEFAULT_OPTS="
#    --cycle --info=hidden
#    --prompt='▍' --pointer='▍' --tabstop=4
#    --color=fg:#a6accd,bg:#0f111a,hl:#464b5d
#    --color=fg+:#a6accd,bg+:#0f111a,hl+:#89ddff
#    --color=info:#0f111a,prompt:#c792ea,pointer:#f07178
#    --color=marker:#c792ea,spinner:#c792ea,header:#464b5d
#    --color=preview-bg:#090b10,border:#464b5d"

# Rose pine colors
# export FZF_DEFAULT_OPTS="
#    --cycle --info=hidden
#    --prompt='▍' --pointer='▍' --tabstop=4
#    --color=fg:#908caa,bg:#191724,hl:#ebbcba
#    --color=fg+:#e0def4,bg+:#26233a,hl+:#ebbcba
#    --color=border:#403d52,header:#31748f,gutter:#191724
#    --color=spinner:#f6c177,info:#9ccfd8,separator:#403d52
#    --color=pointer:#c4a7e7,marker:#eb6f92,prompt:#908caa"

# Material rosepine colors
export FZF_DEFAULT_OPTS="
    --cycle --info=hidden
    --prompt='▍' --pointer='▍' --tabstop=4
    --color=fg:#908caa,bg:#0f111a,hl:#ebbcba
    --color=fg+:#e0def4,bg+:#0f111a,hl+:#ebbcba
    --color=border:#403d52,header:#31748f,gutter:#0f111a
    --color=spinner:#f6c177,info:#9ccfd8,separator:#403d52
    --color=pointer:#c4a7e7,marker:#eb6f92,prompt:#908caa"

export FZF_CTRL_R_OPTS="
    --info=inline --border --reverse
    --preview 'echo {}' --preview-window up:3:hidden:wrap
    --bind 'ctrl-/:toggle-preview'
    --bind 'ctrl-y:execute-silent(echo -n {2..} | pbcopy)+abort'
    --color header:italic
    --header 'Press CTRL-Y to copy command into clipboard'"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_CTRL_T_OPTS="
    --info=hidden --border
    --preview 'bat -n --color=always {}'
    --bind 'ctrl-/:change-preview-window(down|hidden|)'"
export FZF_ALT_C_COMMAND="fd . -t d --hidden"
export FZF_ALT_C_OPTS="--preview='tree -C {} | head -50'"

append_path "$FLUTTER_SDK_ROOT/bin"
append_path "$FLUTTER_SDK_ROOT/bin/cache/dart-sdk/bin"
append_path "$ANDROID_SDK_ROOT/platform-tools/"
append_path "$ANDROID_SDK_ROOT/tools/bin/"
append_path "$ANDROID_SDK_ROOT/emulator"
append_path "$HOME/.cargo/bin"
append_path "$HOME/.pub-cache/bin"
append_path "$GOPATH/bin"
append_path "$HOME/.poetry/bin"
prepend_path "$SCRIPTS"
prepend_path "$SCRIPTS/overrides"
append_path "$HOME/.local/share/nvim/mason/bin"
append_path "/opt/homebrew/bin"
append_path "/opt/homebrew/sbin"
