#!/bin/sh

# Material rosepine colors
export FZF_DEFAULT_OPTS=" \
    --cycle --info=hidden \
    --prompt='▍' --pointer='▍' --tabstop=4 \
    --color=fg:#908caa,bg:#0f111a,hl:#ebbcba \
    --color=fg+:#e0def4,bg+:#0f111a,hl+:#ebbcba \
    --color=border:#403d52,header:#31748f,gutter:#0f111a \
    --color=spinner:#f6c177,info:#9ccfd8,separator:#403d52 \
    --color=pointer:#c4a7e7,marker:#eb6f92,prompt:#908caa"
