'$schema' = 'https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json'
final_space = true
version = 3
[palette]
base = '#191724'
foam = '#9ccfd8'
gold = '#f6c177'
hihigh = '#524f67'
hilow = '#21202e'
himed = '#403d52'
iris = '#c4a7e7'
love = '#eb6f92'
muted = '#6e6a86'
overlay = '#26233a'
pine = '#31748f'
rose = '#ebbcba'
subtle = '#908caa'
surface = '#1f1d2e'
text = '#e0def4'

[secondary_prompt]
template = '▍'
foreground = 'p:himed'
background = 'transparent'

[transient_prompt]
template = "\n<d><{{ if eq .Code 0 }}p:pine{{ else }}p:love{{ end }},p:base>▍</><,p:base>{{ if eq .PWD \"~\" }}home {{ else }}{{ .Folder }} {{ end }}</><#0f111b> </></d>"
foreground = '#93777b'

[[blocks]]
type = 'prompt'
alignment = 'left'

[[blocks.segments]]
style = 'plain'
template = "\n"
type = 'text'

[[blocks.segments]]
style = 'plain'
template = '▍'
foreground = 'green'
background = 'p:hilow'
type = 'status'
foreground_templates = ['{{ if .Error }}red{{end}}']

[blocks.segments.properties]
always_enabled = true

[[blocks.segments]]
style = 'plain'
template = '{{ if and (lt .Percentage 5) (eq .State.String "Discharging") }}█ {{end}}'
foreground = 'red'
background = 'p:hilow'
type = 'battery'

[[blocks.segments]]
style = 'plain'
template = '<b>{{ if eq .PWD "~" }}home {{ else }}{{ .Folder }} {{ end }}</b>'
foreground = 'cyan'
background = 'p:hilow'
type = 'path'

[blocks.segments.properties]
home_icon = 'home'
style = 'folder'

[[blocks]]
type = 'rprompt'
alignment = 'right'
overflow = 'hide'

[[blocks.segments]]
style = 'plain'
template = ' {{ .Name }} {{ .SHLVL }} '
foreground = 'p:himed'
background = 'p:hilow'
type = 'shell'

[[blocks.segments]]
style = 'plain'
template = '{{ if .SSHSession }}  {{ .UserName }}@{{ .HostName }} {{ end }}'
foreground = 'p:gold'
background = 'p:himed'
type = 'session'
