#!/bin/sh

# shellcheck disable=SC1091
. "$HOME/.config/hypr/scripts/commands"

commands_file="$HOME/.config/hypr/scripts/commands"
rcmd="$(grep "()" "${commands_file}" | rofi -dmenu -config ~/.config/rofi/themes/spotlight.rasi -i)"
cmd="$(echo "${rcmd}" | cut -d'(' -f1)"
case "$rcmd" in
*no-notify*) ;;
*) notify-send "$cmd" ;;
esac

$cmd
