#!/bin/sh

: Volume
mute() { v -; }
volume10() { v 1; }
volume20() { v 2; }
volume30() { v 3; }
volume40() { v 4; }
volume50() { v 5; }
volume60() { v 6; }
volume70() { v 7; }
volume80() { v 8; }
volume90() { v 9; }
volume100() { v f; }

: Brightness
brightness10() { b 1; }
brightness20() { b 2; }
brightness30() { b 3; }
brightness40() { b 4; }
brightness50() { b 5; }
brightness60() { b 6; }
brightness70() { b 7; }
brightness80() { b 8; }
brightness90() { b 9; }
brightness100() { b f; }

: Connectivity
wifi() { kitty --class wifi --name wifi -T wifi sudo impala; }
bluetooth() { kitty --class bluetooth --name bluetooth -T bluetooth bluetui; }

: Launcher
open_browser() { firefox 2>&1; }
open_discord() { discord 2>&1; }
open_kitty() { kitty 2>&1; }
open_alacritty() { alacritty 2>&1; }
open_terminal() { open_kitty; }

: Notifications
dismiss_all() { makoctl dismiss -a; }

: System
lock_screen() { hyprlock; }
screenshot_area() { grimblast --notify copysave area; }
screenshot_output() { grimblast --notify --cursor copysave output; }
screenshot_screen() { grimblast --notify --cursor copysave screen; }
reboot() { systemctl reboot; }
restart_hyprland() { hyprctl reload; }

: Screenshot to clipboard only
screenshot_area_clipboard() { grimblast --notify copy area; }
screenshot_output_clipboard() { grimblast --notify --cursor copy output; }
screenshot_screen_clipboard() { grimblast --notify --cursor copy screen; }

: Screenshot to file only
screenshot_area_file() { grimblast --notify save area; }
screenshot_output_file() { grimblast --notify --cursor save output; }
screenshot_screen_file() { grimblast --notify --cursor save screen; }

tmux_peek() { : no-notify && tmux-peek; }
