#!/bin/bash

_have() { type "$1" &>/dev/null; }

source "${XDG_CONFIG_HOME:-$HOME/.config}/shell/envrc"
source "${XDG_CONFIG_HOME:-$HOME/.config}/shell/pathrc"
_have starship && eval "$(starship init bash)"
_have fzf && eval "$(fzf --bash)"
