#!/bin/sh

# Github dark default colors
# TODO(chaitanya): change colors except for background
export FZF_DEFAULT_OPTS="
   --cycle --info=hidden \
   --prompt='▍' --pointer='▍' --tabstop=4 \
   --color=fg:#908caa,bg:#0d1117,hl:#ebbcba \
   --color=fg+:#e0def4,bg+:#0d1117,hl+:#ebbcba \
   --color=border:#403d52,header:#31748f,gutter:#191724 \
   --color=spinner:#f6c177,info:#9ccfd8,separator:#403d52 \
   --color=pointer:#44a7e7,marker:#eb6f92,prompt:#908caa"
